inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - Gemfile
    - app/helpers/password_resets_helper.rb
    - config/environments/development.rb